gpt-4.1-mini-2025-04-14:
  prompt_template: "gpt-4.1-mini-2025-04-14/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4.1-mini-2025-04-14"
    max_tokens: 8192
    temperature: 0