gemini-1.5-flash:
  prompt_template: "gemini-1.5-flash/prompt.txt"
  fn_completions: "google_completions"
  completions_kwargs:
    model_name: "gemini-1.5-flash"
    max_output_tokens: 4096
  batch_size: 1
  fn_completion_parser: null