Llama-4-Scout-17B-16E-Instruct:
  prompt_template: "Llama-4-Scout-17B-16E-Instruct/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "meta-llama/Llama-4-Scout-17B-16E-Instruct"
    max_tokens: 4096
    requires_chatml: True
    client_kwargs:
      base_url: 'https://api.together.xyz'
  batch_size: 1
  fn_completion_parser: null