Mistral-Small-24B-Instruct-2501:
  prompt_template: "Mistral-Small-24B-Instruct-2501/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "mistralai/Mistral-Small-24B-Instruct-2501"
    max_tokens: 4096
    requires_chatml: True
    client_kwargs:
      base_url: 'https://api.together.xyz'
  batch_size: 1
  fn_completion_parser: null