o4-mini-2025-04-16:
  prompt_template: "o4-mini-2025-04-16/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "o4-mini-2025-04-16"
    max_completion_tokens: 8192
  batch_size: 1
  fn_completion_parser: null