gpt-4o-2024-08-06:
  prompt_template: "gpt-4o-2024-08-06/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4o-2024-08-06"
    max_tokens: 4096
  batch_size: 1
  fn_completion_parser: null