gemini-2.5-flash-preview-04-17:
  prompt_template: "gemini-2.5-flash-preview-04-17/prompt.txt"
  fn_completions: "google_completions"
  completions_kwargs:
    model_name: "gemini-2.5-flash-preview-04-17"
    max_output_tokens: 8192
  batch_size: 1
  fn_completion_parser: null